version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flask_app:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/ecommerce
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
